# =======================================
# docker-compose.prod.yml（本番用）
# - backend: gunicorn + uvicorn workers（PostgreSQL 利用）
# - frontend: Nginx で / を配信
# =======================================
services:
  postgres:
    image: postgres:15
    container_name: myapp-postgres
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: myapp
      POSTGRES_DB: myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: myapp-backend:prod
    container_name: myapp-api
    env_file:
      - backend/.env
    environment:
      - APP_ENV=prod
      - DB_URL=postgresql+psycopg2://myapp:myapp@postgres:5432/myapp
    depends_on:
      - postgres
    volumes:
      # ストレージを永続化
      - ./backend/storage:/app/storage
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: prod
      args:
        # ビルド時に API エンドポイントを固定（CDN/ドメインに合わせて差し替え）
        VITE_API_BASE: http://localhost:8000
    image: myapp-frontend:prod
    container_name: myapp-web
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  postgres_data:
