services:
  postgres:
    image: postgres:18
    container_name: myapp-postgres
    env_file:
      - backend/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: myapp-backend:dev
    container_name: myapp-api
    env_file:
      - backend/.env
    environment:
      - APP_ENV=dev
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      # - ./backend/storage:/app/storage
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    image: myapp-frontend:dev
    container_name: myapp-web
    environment:
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  postgres_data:
