services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    command: bash -lc "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_BASE=http://localhost:8000
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api
